#!/bin/bash
# EdgeFlow Dependency Installation Script for raspberry_pi
# Generated by EdgeFlow Deployment Packager

set -e

echo "Installing dependencies for raspberry_pi..."

# Update package lists
apt-get update

# Install system dependencies
apt-get install -y \
    python3 \
    python3-pip \
    python3-dev \
    build-essential

# Install Python dependencies
pip3 install --upgrade pip
pip3 install -r requirements.txt

# Device-specific installations

echo "Dependency installation complete!"
