#!/bin/bash
# EdgeFlow Configuration Script for raspberry_pi
# Generated by EdgeFlow Deployment Packager

set -e

echo "Configuring EdgeFlow for raspberry_pi..."

# Create configuration directory
mkdir -p /etc/edgeflow

# Generate device-specific configuration
cat > /etc/edgeflow/config.json << EOF
{
    "device_type": "raspberry_pi",
    "model_path": "mobilenet_v2_keras.h5",
    "quantize": "int8",
    "buffer_size": 32,
    "memory_limit": 256,
    "optimize_for": "latency"
}
EOF

# Set permissions
chmod 644 /etc/edgeflow/config.json

echo "Configuration complete!"
echo "Config file: /etc/edgeflow/config.json"
