
#!/bin/bash
# EdgeFlow Raspberry Pi Deployment Script
# Generated by EdgeFlow Deployment Packager

set -e

# Configuration
MODEL_PATH="$1"
DEPLOY_PATH="${2:-/opt/edgeflow}"
PYTHON_PATH="/usr/bin/python3"

# Check system requirements
check_requirements() {
    echo "Checking system requirements..."
    
    # Check Python 3
    if ! command -v python3 &> /dev/null; then
        echo "Error: Python 3 is required but not installed"
        exit 1
    fi
    
    # Check TensorFlow Lite
    python3 -c "import tflite_runtime.interpreter" 2>/dev/null || {
        echo "Installing TensorFlow Lite runtime..."
        pip3 install tflite-runtime
    }
    
    # Check NumPy
    python3 -c "import numpy" 2>/dev/null || {
        echo "Installing NumPy..."
        pip3 install numpy
    }
}

# Install dependencies
install_dependencies() {
    echo "Installing dependencies..."
    apt-get update
    apt-get install -y python3-pip python3-dev
    pip3 install --upgrade pip
    pip3 install numpy tflite-runtime
}

# Setup deployment directory
setup_deployment() {
    echo "Setting up deployment directory: $DEPLOY_PATH"
    mkdir -p "$DEPLOY_PATH"/{bin,lib,models,config}
    
    # Copy model
    cp "$MODEL_PATH" "$DEPLOY_PATH/models/"
    
    # Set permissions
    chmod +x "$DEPLOY_PATH/bin"/*
    chown -R root:root "$DEPLOY_PATH"
}

# Create systemd service
create_service() {
    echo "Creating systemd service..."
    cat > /etc/systemd/system/edgeflow.service << EOF
[Unit]
Description=EdgeFlow ML Inference Service
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=$DEPLOY_PATH
ExecStart=$DEPLOY_PATH/bin/inference
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable edgeflow.service
}

# Main installation
main() {
    echo "EdgeFlow Raspberry Pi Deployment"
    echo "================================"
    
    if [ -z "$MODEL_PATH" ]; then
        echo "Usage: $0 <model_path> [deploy_path]"
        exit 1
    fi
    
    check_requirements
    install_dependencies
    setup_deployment
    create_service
    
    echo "Deployment complete!"
    echo "Model: $MODEL_PATH"
    echo "Deploy path: $DEPLOY_PATH"
    echo "Service: edgeflow.service"
    echo ""
    echo "To start the service: systemctl start edgeflow"
    echo "To check status: systemctl status edgeflow"
}

main "$@"
